server:
    port: 8811
spring:
    mvc:
        problemdetails:
            enabled: true
    profiles:
        active: dev
    datasource:
        poolName: BeeCP-Trade-Hall #BeeCP连接池
        username: root
        password: 123456
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/fresh-test?useUnicode=true&tinyInt1isBit=false&characterEncoding=utf-8&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=256&prepStmtCacheSqlLimit=2048
        driverClassName: com.mysql.cj.jdbc.Driver
        maxActive: 10 #连接池最大个数
        initialSize: 3 #连接池初始大小
        maxWait: 120000 #连接借用等待最大时间(毫秒)
        fairMode: false #是否使用公平模式
        validTestSql: select 1 #连接有效性测试SQL语句
        validAssumeTime: 5000 #连接测试的间隔时间(毫秒)
        asyncCreateInitConnection: true #以异步的方式创建连接池
        printRuntimeLog: true #打印扫描前后池内情况：使用数，闲置数，等待数

    # redis 配置
    data:
        redis:
            # 地址
            host: 192.168.217.4
            port: 6379
            # 数据库索引
            database: 2
            # 密码
            #password: SDNC@redis#1024

beetlsql:
    # sqlManage，可以配置多个，用逗号隔开
    sqlManagers: primarySQLManager
    # primarySQLManager 的配置
    primarySQLManager:
        # 数据源名称
        ds: primaryDataSource
        # 指明 mapper 类的结尾，扫描到以 Mapper 结尾的类会为其自动生成代理类，注册为 Spring 的 Bean
        # 默认扫描 Mapper 结尾，可不配置。如果你不是 xxxMapper 这样以 Mapper 结尾的，则需要配置
        daoSuffix: Dao
        # 要扫描 Mapper 的包名
        basePackage: com.sdnc.trade.infrastructure.dao
        # POJO 和数据表列的名称转换，如驼峰 userName 转换为下划线的 user_name
        nameConversion: org.beetl.sql.core.UnderlinedNameConversion
        # 数据库方言
        dbStyle: org.beetl.sql.core.db.MySqlStyle
        # 是否是开发模式
        dev: true

# Token校验忽略的URL
passport:
    url:
        ignore:
            - /qry/area/page
            - /qry/area/allList

management:
    server:
        port: 50000 # 启用独立运维端口
    endpoint: # 开启health端点
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                base-path: /actuator # 指定上下文路径，启用相应端点
                include: health
